__author__ = "Ron Williams"
__author_email__ = "becker.williams@gmail.com"
__copyright__ = "Copyright (C) 2024 Ron Williams, All Rights Reserved"
__version__ = "1.0.1"
__description__ = "Moduli Assembly"
